### ISSUE TITLE
Using multiple threads results in deadlock of the hisparc-update (updatehistograms job)

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#242] opened 2019-01-03 14:40 UTC
If we set `USE_MULTIPROCESSING = True` in settings.py, the publicdb crashes. Unfortunately debugging is hard because of the not so useful error traceback.

**Comment by 153957** [comment] 2019-01-03 14:43
Does it also fail when using `USE_MULTIPROCESSING = False`?
If so you can:
- temporarily disable multiprocessing
- run processing again manually
- find and fix the bug
- redeploy
- reenable multiprocessing.

**Comment by kaspervd** [comment] 2019-01-03 14:45
No, unfortunately it does work if USE_MULTIPROCESSING = False

**Comment by 153957** [comment] 2019-01-03 14:48
Ah, That is unfortunate!

**Comment by tomkooij** [comment] 2019-01-08 08:35
ATM there are no `RuntimeErrors` but the daily update just seems to stall/hang on doing the `histograms` job. We need to enable some DEBUG output to investigate.

**Comment by tomkooij** [comment] 2019-01-09 06:31
I turned on `logging.DEBUG`. There seems to be a deadlock in `update_histograms()` in the multiprocessing.Pool taskmanager thing:

https://github.com/HiSPARC/publicdb/blob/cd33a6a1ac617a3ac60e3c41c657989e7ec778f5/publicdb/histograms/jobs.py#L206

All workers (12!) finish event histrogram tasks and at some point just seem to wait for new work or waiting for each other to finish. (Yikes!)

This will probably not be easy to debug. I switch back to `MULTIPROCESSING = False` for now.

**Comment by tomkooij** [comment] 2019-01-09 08:15
I can *unfortunately* reproduce a `multiprocessing.Pool()` deadlock (CPython bug): https://bugs.python.org/issue29759

There is a script `~hisparc/try_deadlock.sh` on pique that reproducably causes deadlocks.

**Comment by tomkooij** [comment] 2019-01-09 11:08
It may not even be the above deadlock, but a much more common cpython bug: https://bugs.python.org/issue6721  . Apparently logging + multiprocessing causes frequent deadlocks.

This is fixed in python 3.7 :-)

I'm not going to spend anymore time on this. I'll have a look at the python3 work.

**Comment by kaspervd** [comment] 2019-01-09 11:40
Thanks a lot @tomkooij!

**Comment by 153957** [comment] 2022-07-16 07:25
This should be fixed by #283, since we update to a newer Python version (i.e. ≥3.7.1).

Would we need to reenable some setting which is currently turned off?

**Comment by davidfokkema** [comment] 2022-07-27 10:48
After the update, `MULTIPROCESSING = True` should be set again?

**Comment by 153957** [comment] 2022-07-27 12:22
Yes

**Closed** 2022-11-22 07:19 UTC
